castore:
  upload_dir: /var/kraken/cache/kraken-proxy-upload/
  cache_dir:  /var/kraken/cache/kraken-proxy-cache/
  capacity: 1024

zap:
  level: info
  development: false
  encoding: console
  disableStacktrace: true
  encoderConfig:
    messageKey: message
    nameKey: logger_name
    levelKey: level
    timeKey: ts
    callerKey: caller
    stacktraceKey: stack
    levelEncoder: capital
    timeEncoder: iso8601
    durationEncoder: seconds
    callerEncoder: short
  outputPaths:
  - stdout
  - /var/kraken/log/kraken-proxy-stdout.log
  errorOutputPaths:
  - stderr
  - /var/kraken/log/kraken-proxy-stderr.log

metrics:
  m3:
    service: kraken-proxy

registry:
  docker:
    version: 0.1
    log:
      level: error
    http:
      net: unix
      addr: /tmp/kraken-proxy-registry.sock

registryoverride:
  listener:
    net: unix
    addr: /tmp/kraken-proxy-registry-override.sock

nginx:
  name: kraken-proxy
  log_dir: /var/kraken/log/
  cache_dir: /var/kraken/cache/kraken-proxy-nginx/
