zap:
  level: info
  development: false
  disableStacktrace: true
  encoding: console
  encoderConfig:
    messageKey: message
    nameKey: logger_name
    levelKey: level
    timeKey: ts
    callerKey: caller
    stacktraceKey: stack
    levelEncoder: capital
    timeEncoder: iso8601
    durationEncoder: seconds
    callerEncoder: short
  outputPaths:
  - stdout
  - /var/kraken/log/kraken-tracker-stdout.log
  errorOutputPaths:
  - stderr
  - /var/kraken/log/kraken-tracker-stderr.log

logging:
  level: info
  stdout: true
  sentry:
    enabled: false
    tags:
      deployment: default

peerhandoutpolicy:
  priority: completeness

metrics:
  m3:
    service: kraken

trackerserver:
  listener:
    net: unix
    addr: /tmp/kraken-tracker.sock

nginx:
  name: kraken-tracker
  log_dir: /var/kraken/log/
  cache_dir: /var/kraken/cache/kraken-tracker-nginx/
