zap:
  level: info
  development: false
  encoding: console
  disableStacktrace: true
  encoderConfig:
    messageKey: message
    nameKey: logger_name
    levelKey: level
    timeKey: ts
    callerKey: caller
    stacktraceKey: stack
    levelEncoder: capital
    timeEncoder: iso8601
    durationEncoder: seconds
    callerEncoder: short
  outputPaths:
  - stdout
  - /var/kraken/log/kraken-origin-stdout.log
  errorOutputPaths:
  - stderr
  - /var/kraken/log/kraken-origin-stderr.log

metainfogen:
  piece_lengths:
    0: 4MB # Use 4MB piece lengths for all file sizes (for now).

peer_id_factory: addr_hash

scheduler:
  log:
    timeEncoder: iso8601
  torrentlog:
    disable: true

metrics:
  m3:
    service: kraken-origin

localdb:
  source: /var/kraken/cache/kraken-origin-origin.db

castore:
  upload_dir: /var/kraken/cache/kraken-origin-upload/
  cache_dir:  /var/kraken/cache/kraken-origin-cache/

blobserver:
  listener:
    net: unix
    addr: /tmp/kraken-origin.sock

nginx:
  name: kraken-origin
  log_dir: /var/kraken/log/
  cache_dir: /var/kraken/cache/kraken-origin-nginx/
