localdb:
  source: /var/kraken/cache/kraken-build-index-index.db

store:
  upload_dir: /var/kraken/cache/kraken-build-index-upload/
  cache_dir: /var/kraken/cache/kraken-build-index-cache/

tag_store:
  write_through: true

zap:
  level: info
  development: false
  encoding: console
  disableStacktrace: true
  encoderConfig:
    messageKey: message
    nameKey: logger_name
    levelKey: level
    timeKey: ts
    callerKey: caller
    stacktraceKey: stack
    levelEncoder: capital
    timeEncoder: iso8601
    durationEncoder: seconds
    callerEncoder: short
  outputPaths:
  - stdout
  - /var/kraken/log/kraken-build-index-stdout.log
  errorOutputPaths:
  - stderr
  - /var/kraken/log/kraken-build-index-stderr.log

metrics:
  m3:
    service: kraken-build-index

tagserver:
  listener:
    net: unix
    addr: /tmp/kraken-build-index.sock

nginx:
  name: kraken-build-index
  log_dir: /var/kraken/log/
  cache_dir: /var/kraken/cache/kraken-build-index-nginx/
